### ISSUE TITLE
drop html extension from twig task globs?

### ISSUE THREAD

**Issue by olets** [nmcteam/mulch#12]
The twig documentation makes a point of saying

> It can generate any text-based format (HTML, XML, CSV, LaTeX, etc.). It doesn't have a specific extension, .html or .xml are just fine. ([source](http://twig.sensiolabs.org/doc/templates.html))

I've read that .twig is commonly used on twig html files, and .[file type].twig is a common way of making a file as part of a twig project (e.g. .html.twig, .json.twig).

This all makes me think mulch shouldn't require .html. Thoughts?

**Comment by JoelSutherland** [comment]
Yeah that makes sense

**Comment by olets** [comment]
https://github.com/nmcteam/mulch/pull/13
